### ISSUE TITLE
Add this image as default for okd's imagestreams list

### ISSUE THREAD

**Issue by cmoulliard** [rh-openjdk/redhat-openjdk-containers#37]
By default, the java s2i image is not included natively within the [community list](https://github.com/openshift/library/tree/master/community) of okd.

This is really disadvantageous as we can't install SpringBoot, Vert.x or even Thorntail projects on okd excepted if we install manually this java s2i imagestream (or if we configure minishift to use the addon xpaas able to install the official redhat java s2i image)

Is it possible for you to submit a PR to the openshift/library project in order to have it part of okd ?

**Comment by jmtd** [comment]
> By default, the java s2i image is not included natively within the community list of okd.

This seems like an excellent idea and something to do after we have first shipped a community build of this image, which we haven't done yet. Soon :)

**Comment by apupier** [comment]
not sure if it is the same image but several images has been added including redhat-openjdk18-openshift:

![image](https://user-images.githubusercontent.com/1105127/51333084-4d340600-1a7d-11e9-9ac0-494e5922221b.png)

**Comment by apupier** [comment]
my bad these images were added by a specific addon (Che one). The issue is still very relevant.

EDIT: seems i was again wrong :'( these images are added by xpaas-addon in minishift. they were no more added for me because the che addon was failing but I think that it remains interesting that the java is added to okd
