### ISSUE TITLE
RFE: Gradle support

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#64]
This S2I Builder image IMHO really should ("out of the box") support Gradle in addition to Maven.

We can take (strong) inspiration from the following "prior art" work done to implement this here:

* https://developers.redhat.com/blog/2018/12/18/openshift-java-s2i-builder-java-11-grade/
* https://github.com/fabric8io-images/s2i/issues/118
* https://github.com/fabric8io-images/s2i/pull/121
* https://github.com/fabric8io-images/s2i/pull/151
* https://github.com/fabric8io-images/s2i/pull/158/files
* https://github.com/fabric8io-images/s2i/issues/150 (still TBD)
* https://github.com/fabric8io-images/s2i/issues/161 (example end-user interest)

**Comment by vorburger** [comment]
@jmtd before I may sink any time into working on this, I would like to "officially" propose Gradle support, for the product images, not just the community edition. What would be the appropriate issue tracker to start a discussion about that?

**Comment by jmtd** [comment]
The best answer would be [a JIRA issue in the jboss.org JIRA, CLOUD project, "Java S2I" component](issues.jboss.org/browse/CLOUD) at the moment. We haven't migrated out of that project even though Cloud Enablement has closed down, so there isn't a better answer yet. And yes please, that would be good to do; I'm nervous about even reviewing or merging Gradle support at this point in time due to not being able to gauge the business interest against the costs involved.

**Comment by jmtd** [comment]
Just FYI, my current TODO priorities are: Openshift-Next (OCP specifically) support and RHEL8 base image support. Just behind those are community image matters.

**Comment by vorburger** [comment]
https://issues.jboss.org/browse/CLOUD-3107

**Comment by jmtd** [comment]
I don't plan to work on this. If someone wants to step up and do it, re-open this issue so we can discuss it. Thanks!
